application: davidzessen
version: 1
runtime: python
api_version: 1

handlers:

- url: /datastore/*.*
  script: datastore.py

- url: /overzichten/*.*
  script: overzichten.py

- url: /afspraakplanningpost
  script: main.py

- url: /beheerder
  script: main.py

- url: /docentafspraak
  script: main.py
  
- url: /leerlingafspraak
  script: main.py  

- url: /nextstep
  script: insert.py
  
- url: /plannen
  script: main.py
  
- url: /plannenpost
  script: main.py
  
- url: /
  script: main.py
  
- url: /chat
  script: main.py
  
- url: /chatajaxhandler
  script: main.py
  
- url: /logout
  script: main.py

- url: /accountsettings
  script: main.py

- url: /accountwachtwoordpost
  script: main.py
  
- url: /insert/*.*
  script: insert.py
  
- url: /authenticate
  script: main.py
  
- url: /images
  static_dir: images
  
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css
  
- url: /html
  static_dir: html