application: davidzessen
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /insert/*.*
  script: insert.py
  
- url: /images
  static_dir: images
  
- url: /js
  static_dir: js
  